# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import datetime
import django.contrib.auth.models
import django.utils.timezone
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(null=True, verbose_name='last login', blank=True)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=30, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name', blank=True)),
                ('last_name', models.CharField(max_length=30, verbose_name='last name', blank=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address', blank=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('facility_id', models.CharField(max_length=30, null=True)),
                ('fcm_token', models.CharField(max_length=512, null=True)),
                ('groups', models.ManyToManyField(related_query_name='user', related_name='user_set', to='auth.Group', blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(related_query_name='user', related_name='user_set', to='auth.Permission', blank=True, help_text='Specific permissions for this user.', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('referral_id', models.CharField(max_length=30, serialize=False, primary_key=True)),
                ('referral_date', models.DateField(null=True, blank=True)),
                ('expiry_date', models.DateField(null=True, blank=True)),
                ('language', models.CharField(max_length=20, null=True, blank=True)),
                ('id_client', models.IntegerField(null=True, blank=True)),
                ('notification_client_id', models.IntegerField(null=True, blank=True)),
                ('notification_facility_id', models.IntegerField(null=True, blank=True)),
                ('mode', models.IntegerField(null=True, blank=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
            ],
            options={
                'db_table': 'appointment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(serialize=False, primary_key=True)),
                ('sex', models.CharField(max_length=10, null=True, blank=True)),
                ('age', models.IntegerField(null=True, blank=True)),
                ('phone', models.CharField(max_length=100, null=True, blank=True)),
                ('occupation', models.IntegerField(null=True, blank=True)),
                ('garment_id', models.CharField(max_length=100, null=True, blank=True)),
                ('adr_street', models.CharField(max_length=255, null=True, blank=True)),
                ('adr_village', models.CharField(max_length=255, null=True, blank=True)),
                ('adr_commune', models.CharField(max_length=255, null=True, blank=True)),
                ('adr_district', models.CharField(max_length=255, null=True, blank=True)),
                ('adr_province', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DwProjet',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('id_parent', models.IntegerField()),
                ('id_type_niveau', models.IntegerField()),
                ('short_code_calculated', models.CharField(max_length=40, null=True, blank=True)),
                ('code_questionnaire', models.CharField(max_length=20)),
                ('nom_table', models.CharField(max_length=25, null=True, blank=True)),
                ('type_projet', models.CharField(max_length=2)),
                ('commentaire', models.TextField(null=True, blank=True)),
                ('affiche', models.IntegerField(null=True, blank=True)),
                ('url', models.CharField(max_length=80, null=True, blank=True)),
                ('url_xform', models.CharField(max_length=80, null=True, blank=True)),
                ('credential', models.TextField(null=True, blank=True)),
                ('code_sujet', models.CharField(max_length=20, null=True, blank=True)),
                ('doublon', models.CharField(max_length=80, null=True, blank=True)),
                ('need_total', models.IntegerField(null=True, blank=True)),
                ('xls_form', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dw_projet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DwQuestionnaire',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('id_projet', models.IntegerField()),
                ('questionnaire', models.TextField()),
                ('nom_colonne', models.CharField(max_length=80)),
                ('path', models.CharField(max_length=80, null=True, blank=True)),
                ('libelle_fr', models.CharField(max_length=254)),
                ('libelle_us', models.CharField(max_length=254, null=True, blank=True)),
                ('data_type', models.CharField(max_length=40, null=True, blank=True)),
                ('date_format', models.CharField(max_length=10, null=True, blank=True)),
                ('rang', models.IntegerField(null=True, blank=True)),
                ('sel', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dw_questionnaire',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MessagesLog',
            fields=[
                ('id_message', models.AutoField(serialize=False, primary_key=True)),
                ('date_sent', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('status', models.CharField(max_length=250, null=True, blank=True)),
                ('content_sms', models.TextField(null=True, blank=True)),
                ('from_number', models.CharField(max_length=100, null=True, blank=True)),
                ('to_number', models.CharField(max_length=100, null=True, blank=True)),
                ('id_actor', models.IntegerField(null=True, blank=True)),
                ('id_recipient', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'messages_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('occupation_name', models.CharField(max_length=100, null=True, blank=True)),
            ],
            options={
                'db_table': 'occupation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReferralOperation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('referral_id', models.CharField(max_length=20, null=True, blank=True)),
                ('actor_id', models.IntegerField(null=True, blank=True)),
                ('last_actor_id', models.IntegerField(null=True, blank=True)),
                ('referred_services', models.TextField(null=True, blank=True)),
                ('other_services', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(null=True, blank=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('is_completed', models.CharField(max_length=4, null=True, blank=True)),
                ('has_alternative', models.CharField(max_length=4, null=True, blank=True)),
                ('provider', models.CharField(max_length=255, null=True, blank=True)),
                ('redeem_date', models.DateField(null=True, blank=True)),
                ('facility_id', models.CharField(max_length=20, null=True, blank=True)),
            ],
            options={
                'db_table': 'referral_operation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReferredServices',
            fields=[
                ('service_name', models.CharField(max_length=250, serialize=False, primary_key=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
            ],
            options={
                'db_table': 'referred_services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('id_niveau', models.IntegerField(null=True)),
                ('id_soumission', models.CharField(max_length=35, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('code_questionnaire', models.CharField(max_length=20)),
                ('date_soumission', models.DateField(null=True)),
                ('date_soumission_u', models.CharField(max_length=6)),
                ('date_modification', models.DateField()),
                ('date_modification_u', models.CharField(max_length=6, null=True)),
                ('imported', models.IntegerField(null=True)),
                ('short_code_calculated', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('datasender_id', models.CharField(max_length=20, null=True)),
                ('datasender_name', models.CharField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'sms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmsApi',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('id_niveau', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('code_questionnaire', models.CharField(max_length=20)),
                ('date_soumission', models.DateField()),
                ('date_soumission_u', models.CharField(max_length=6)),
                ('imported', models.IntegerField()),
                ('short_code_calculated', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15, null=True, blank=True)),
            ],
            options={
                'db_table': 'sms_api',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmsFac',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('id_niveau', models.IntegerField(null=True, blank=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('code_questionnaire', models.CharField(max_length=20)),
                ('date_soumission', models.DateField()),
                ('date_soumission_u', models.CharField(max_length=6)),
                ('imported', models.IntegerField(null=True)),
                ('short_code_calculated', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, blank=True)),
                ('quest_1', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_2', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_3', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_4', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_5', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_6', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_7', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_8', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_9', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_10', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_11', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_12', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_13', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_14', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_15', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_16', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_17', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_18', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_19', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_20', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_21', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_22', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_23', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_24', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_25', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_26', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_27', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_28', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_29', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_30', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_31', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_32', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_33', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_34', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_35', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_36', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_37', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_38', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_39', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_40', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_41', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_42', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_43', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_44', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_45', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_46', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_47', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_48', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_49', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_50', models.CharField(max_length=250, null=True, blank=True)),
            ],
            options={
                'db_table': 'sms_fac',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmsFacTmp',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('id_niveau', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('code_questionnaire', models.CharField(max_length=20)),
                ('date_soumission', models.DateField()),
                ('date_soumission_u', models.CharField(max_length=6)),
                ('imported', models.IntegerField(null=True)),
                ('short_code_calculated', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, blank=True)),
                ('quest_1', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_2', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_3', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_4', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_5', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_6', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_7', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_8', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_9', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_10', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_11', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_12', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_13', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_14', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_15', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_16', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_17', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_18', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_19', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_20', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_21', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_22', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_23', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_24', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_25', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_26', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_27', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_28', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_29', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_30', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_31', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_32', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_33', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_34', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_35', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_36', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_37', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_38', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_39', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_40', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_41', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_42', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_43', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_44', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_45', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_46', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_47', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_48', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_49', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_50', models.CharField(max_length=250, null=True, blank=True)),
            ],
            options={
                'db_table': 'sms_fac_tmp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmsLoc',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('id_niveau', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('code_questionnaire', models.CharField(max_length=20)),
                ('date_soumission', models.DateField()),
                ('date_soumission_u', models.CharField(max_length=6)),
                ('imported', models.IntegerField(null=True)),
                ('short_code_calculated', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, blank=True)),
                ('quest_1', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_2', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_3', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_4', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_5', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_6', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_7', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_8', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_9', models.CharField(max_length=250, null=True, blank=True)),
            ],
            options={
                'db_table': 'sms_loc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmsLocTmp',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('id_niveau', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('code_questionnaire', models.CharField(max_length=20)),
                ('date_soumission', models.DateField()),
                ('date_soumission_u', models.CharField(max_length=6)),
                ('imported', models.IntegerField(null=True)),
                ('short_code_calculated', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, blank=True)),
                ('quest_1', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_2', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_3', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_4', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_5', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_6', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_7', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_8', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_9', models.CharField(max_length=250, null=True, blank=True)),
            ],
            options={
                'db_table': 'sms_loc_tmp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmsReg',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('id_niveau', models.IntegerField(null=True, blank=True)),
                ('status', models.CharField(max_length=10, null=True, blank=True)),
                ('code_questionnaire', models.CharField(max_length=20, null=True, blank=True)),
                ('date_soumission', models.DateField(null=True, blank=True)),
                ('date_soumission_u', models.CharField(max_length=6, null=True, blank=True)),
                ('imported', models.IntegerField(null=True, blank=True)),
                ('short_code_calculated', models.IntegerField(null=True, blank=True)),
                ('phone_number', models.CharField(max_length=15, null=True, blank=True)),
                ('quest_1', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_2', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_3', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_4', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_5', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_6', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_7', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_8', models.CharField(max_length=250, null=True, blank=True)),
            ],
            options={
                'db_table': 'sms_reg',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmsRegTmp',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('id_niveau', models.IntegerField(null=True, blank=True)),
                ('status', models.CharField(max_length=10, null=True, blank=True)),
                ('code_questionnaire', models.CharField(max_length=20, null=True, blank=True)),
                ('date_soumission', models.DateField(null=True, blank=True)),
                ('date_soumission_u', models.CharField(max_length=6, null=True, blank=True)),
                ('imported', models.IntegerField(null=True, blank=True)),
                ('short_code_calculated', models.IntegerField(null=True, blank=True)),
                ('phone_number', models.CharField(max_length=15, null=True, blank=True)),
                ('quest_1', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_2', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_3', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_4', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_5', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_6', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_7', models.CharField(max_length=250, null=True, blank=True)),
                ('quest_8', models.CharField(max_length=250, null=True, blank=True)),
            ],
            options={
                'db_table': 'sms_reg_tmp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VoucherCode',
            fields=[
                ('unique_id', models.CharField(max_length=10, serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'voucher_code',
                'managed': True,
            },
        ),
    ]
